# Generated by Django 3.2.11 on 2022-01-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('contact', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=50)),
                ('Password', models.CharField(max_length=16)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
