from django.contrib import admin
from django.urls import path
from app import views
urlpatterns = [
    path('', views.home, name = 'home'),
    path('about', views.about, name = 'about'),
    path('courses', views.courses, name = 'courses'),
    path('register', views.register, name = 'register'),
    path('login', views.login, name = 'login'),
    path('contact', views.contact, name = 'contact'),
    path('firstyear', views.firstyear, name = 'firstyear'),
    path('ourteam', views.ourteam, name = 'ourteam'),
    path('IT2', views.IT2, name = 'IT2'),
    path('IT3', views.IT3, name = 'IT3'),
    path('IT4', views.IT4, name = 'IT4'),
    path('civil2', views.civil2, name = 'civil2'),
    path('civil3', views.civil3, name = 'civil3'),
    path('civil4', views.civil4, name = 'civil4'),
    path('electrical2', views.electrical2, name = 'electrical2'),
    path('electrical3', views.electrical3, name = 'electrical3'),
    path('electrical4', views.electrical4, name = 'electrical4'),
    path('chemistry', views.chemistry,name = 'chemistry'),
    path('Physics', views.Physics,name = 'Physics'),
    path('maths1', views.maths1,name = 'maths1'),
    path('maths2', views.maths2,name = 'maths2'),
    path('basic_electrical', views.basic_electrical,name = 'basic_electrical'),
    
    path('mechanical', views.mechanical,name = 'mechanical'),
    path('AI', views.AI,name = 'AI'),
    path('ET', views.ET,name = 'ET'),
    path('softskill', views.softskill,name = 'softskill'),
    path('pps', views.pps,name = 'pps'),
    path('electronics', views.electronics,name ="electronics"),
    path('register',views.register,name='register'),
    path('ds',views.ds,name='ds'),
    path('coa',views.coa,name='coa'),
    path('maths4',views.maths4,name='maths4'),
    path('discrete',views.discrete,name='discrete'),
    path('python',views.python,name='python'),
    path('uhv',views.uhv,name='uhv'),
    path('toa',views.toa,name='toa'),
    path('os',views.os,name='os'),
    path('mp',views.mp,name='mp'),
    path('esc',views.esc,name='esc'),
    path('css',views.css,name='css'),
    path('login',views.login,name='login'),
   
    
]